back/api/config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :albums
  resources :users
  resources :artists

  get "up" => "rails/health#show", as: :rails_health_check
  get "users", to: "users#index"
  get "users/:id", to: "users#show"

  get "albums", to: "albums#index"
  get "albums/:id", to: "albums#show"
  post "albums/create", to:"albums#create"

  delete '/delete/:id', to: 'albums#destroy'
  put '/update/:id', to: 'albums#update'

  post '/login', to: 'users#login'
  post '/auth/register', to: 'users#create'

  get "/artists", to: "artists#index"

end

back/api/app/models/album.rb
class Album < ApplicationRecord

end

back/api/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

back/api/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

back/api/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token, only: [:create]

  # GET /albums or /albums.json
  def index
    user_id = params[:user_id]
    @albums = Album.where(user_id: user_id).page(params[:page]).per(params[:limit] || 10)
    render json: {
      albums: @albums.map { |album| album.serializable_hash },
      metadata: {
        page: @albums.current_page,
        limit: @albums.limit_value,
        total_pages: @albums.total_pages,
        total_count: @albums.total_count
      }
    }
  end  

  # GET /albums/1 or /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
    render json: @album 
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums/create or /albums.json
  def create
    Rails.logger.info "DADOS VINDO DO FRONT: #{album_params}"

    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.json { render :show, status: :created, location: @album, message: "Album was successfully created." }
      else
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.json { render :show, status: :ok, location: @album, message: "Album was successfully updated." }
      else
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy!

    respond_to do |format|
      format.json { head :no_content, message: "Album was successfully destroyed."  }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:name_album, :year_album, :artist, :user_id)
    end
end

back/api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def authorized
    user = User.find_by(email: params["user"][:email], password: params["user"][:password])
    if user
      token = generate_token(user)
      render json: { token: token }, status: :ok
    else
      render json: { message: 'Invalid email or password' }, status: :unauthorized
    end
  end

  private

  def generate_token(user)
    JWT.encode({ user_id: user.id }, 'eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxfQ.swLG_V3aYLyR4gOhaX8yX5xyD107Swm9thl4vJGBVCw', 'HS256')
  end
end

back/api/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    def index
      response = Faraday.get('https://europe-west1-madesimplegroup-151616.cloudfunctions.net/artists-api-controller') do |req|
        req.headers['Authorization'] = 'Basic ZGV2ZWxvcGVyOlpHVjJaV3h2Y0dWeQ=='
        req.headers['Content-Type'] = 'application/json'
      end
  
      render json: response.body
    end
end

back/api/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  skip_before_action :verify_authenticity_token, only: [:login, :create]

  # GET /users or /users.json
  def index
    @users = User.all
    render json: @users 
  end

  # GET /users/1 or /users/1.json
  def show
  end

  def login
    user_params = params.require(:user).permit(:email, :password)

    user = User.find_by(email: user_params[:email]).try(:authenticate, user_params[:password])
        
    if user
      token = encode_token({ user_id: user.id })
      session[:user_id] = user.id
      render json: {
        logged_in: true,
        user: user.as_json(only: [:id, :email, :name, :full_name, :username, :role, :created_at, :updated_at]),
        token: token
      }, status: :created
    else
      render json: { status: 401 }, status: :unauthorized
    end
  end
   

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.json { render :show, status: :created, location: @user }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.json { render :show, status: :ok, location: @user }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      full_name = "#{params[:full_name][:firstName]} #{params[:full_name][:lastName]}"
      params.permit(:email, :username, :password, :role).merge(full_name: full_name)      
    end

    def encode_token(payload)
      JWT.encode(payload, 'eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxfQ.swLG_V3aYLyR4gOhaX8yX5xyD107Swm9thl4vJGBVCw')
    end
end

back/api/app/helpers/albums_helper.rb
module AlbumsHelper
end

back/api/app/helpers/application_helper.rb
module ApplicationHelper
end

back/api/app/helpers/users_helper.rb
module UsersHelper
end

back/api/app/views/albums/_album.html.erb
<div id="<%= dom_id album %>">
  <p>
    <strong>Artist:</strong>
    <%= album.artist %>
  </p>

  <p>
    <strong>Name album:</strong>
    <%= album.name_album %>
  </p>

  <p>
    <strong>Year album:</strong>
    <%= album.year_album %>
  </p>

</div>

back/api/app/views/albums/_form.html.erb
<%= form_with(model: album) do |form| %>
  <% if album.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% album.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :artist, style: "display: block" %>
    <%= form.text_field :artist %>
  </div>

  <div>
    <%= form.label :name_album, style: "display: block" %>
    <%= form.text_field :name_album %>
  </div>

  <div>
    <%= form.label :year_album, style: "display: block" %>
    <%= form.text_field :year_album %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

back/api/app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render "form", album: @album %>

<br>

<div>
  <%= link_to "Show this album", @album %> |
  <%= link_to "Back to albums", albums_path %>
</div>

back/api/app/views/albums/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Albums</h1>

<div id="albums">
  <% @albums.each do |album| %>
    <%= render album %>
    <p>
      <%= link_to "Show this album", album %>
    </p>
  <% end %>
</div>

<%= link_to "New album", new_album_path %>

back/api/app/views/albums/new.html.erb
<h1>New album</h1>

<%= render "form", album: @album %>

<br>

<div>
  <%= link_to "Back to albums", albums_path %>
</div>

back/api/app/views/albums/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @album %>

<div>
  <%= link_to "Edit this album", edit_album_path(@album) %> |
  <%= link_to "Back to albums", albums_path %>

  <%= button_to "Destroy this album", @album, method: :delete %>
</div>

back/api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Api</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

back/api/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :full_name, style: "display: block" %>
    <%= form.text_field :full_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.label :role, style: "display: block" %>
    <%= form.text_field :role %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

back/api/app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Full name:</strong>
    <%= user.full_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= user.role %>
  </p>

</div>

back/api/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

back/api/app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

back/api/app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

back/api/app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>